<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A Contract is a haulage job offered on the open market: move N units of
 * a commodity from an origin city to a destination city before a deadline
 * for a payout, with a penalty for failure. Contracts are generated by the
 * world economy and claimed by companies. Once claimed they belong to a
 * company until fulfilled or expired.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('contracts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('commodity_id')->constrained();
            $table->unsignedBigInteger('origin_city_id');
            $table->unsignedBigInteger('destination_city_id');

            // Null while on the open market; set when a company accepts it.
            $table->foreignId('company_id')->nullable()->constrained()->nullOnDelete();

            // open | accepted | in_progress | completed | failed | expired
            $table->string('status')->default('open');

            $table->unsignedInteger('units');
            $table->decimal('distance_km', 10, 2);
            $table->bigInteger('payout');          // ₡ cents on success
            $table->bigInteger('penalty');         // ₡ cents on failure
            $table->unsignedInteger('reputation_reward')->default(5);

            $table->unsignedTinyInteger('difficulty')->default(1); // 1..5 stars
            $table->boolean('is_rush')->default(false);
            $table->boolean('is_fragile')->default(false);

            $table->timestamp('deadline_at');      // must be delivered by
            $table->timestamp('expires_at');       // offer disappears from market if unclaimed
            $table->timestamps();

            $table->index('status');
            $table->index(['status', 'origin_city_id']);
            $table->index('company_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('contracts');
    }
};
